#!/usr/bin/python

import re, sys
from subprocess import check_output

commit_msg_filepath = sys.argv[1]
branch = (check_output(["git", "symbolic-ref", "--short", "HEAD"]).decode("utf-8").strip())

regex = r"^[A-Z]{1,9}-[0-9]{1,9}"

found_obj = re.match(regex, branch)

if found_obj:
    prefix = found_obj.group(0)
    with open(commit_msg_filepath, "+r") as f:
        commitMsg = f.read()
        if commitMsg.find(prefix) == -1:
            f.seek(0,0) # correctly positions issue_number when writing commit message
            f.write(f"[{prefix}] {commitMsg}")