#!/usr/bin/python

import subprocess, sys

def get_story():
    branchname = subprocess.check_output(["/usr/bin/git", "symbolic-ref", "HEAD"])
    
    # This looks like: ref/heads/feature/CRE-0000-12345
    args = branchname.split('/')
    if len(args) != 4:
        raise ValueError("Branch name not in expected format.")
    story = int(branchname.split('/')[2])
    return story

def prepend_commit_msg(text):
    msgfile = sys.argv[1]

    with open(msgfile) as f:
        contents = f.read()
    
    with open(msgfile, 'w') as f:
        if not contents.startswith(text):
            f.write(text)
        f.write(contents)

def main():
    try:
        story = get_story()
        header = "[#%d] " % story
        prepend_commit_msg(header)
    except:
        pass

if __name__ == '__main__':
    main()