name: Update git-hooks if changes we're made to .git-hooks folder.
on: 
  # Triggers the workflow on push request,
  # but only for the feature branches
  push:
    paths: 
      - '.git-hooks/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest version of git-hooks to repo.
        run: |
          chmod +x ./.git-hooks/*
          cd .git-hooks
          ./install-hooks.sh
          ls -l ../.git/hooks
        shell: bash