# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: no-commit-to-branch
-   repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
    -   id: giticket
        args: ['--regex=(develop|release|((feature|task|bugfix|hotfix)\/SRE+(-|_)[0-9]+(-|_).+))', '--format={ticket} {commit-msg}']
