# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: no-commit-to-branch
-   repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.1.1
    hooks:
      - id: conventional-commits
# -   repo: https://github.com/avilaton/add-msg-issue-prefix-hook
#     rev: v0.0.5
#     hooks:
#         -   id: add-msg-issue-prefix
#             args:
#                 - --template=[{}]
