# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: no-commit-to-branch
-   repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
    -   id: giticket
# -   repo: https://github.com/fearfactor3/git-administration-code
#     rev: 077d32089e71210e1f72d5803f3e978e3606f49e
#     hooks:
#     -   id: commit-msg
