name: Update git-hooks if changes were made to .git-hooks folder.
on: 
  push:
#    paths: 
#      - '.git-hooks/**'
jobs: 
  git-administration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest version of git-hooks to repo.
        run: |
          chmod +x ./.git-hooks/*
          cd .git-hooks
          ./install-hooks.sh
          ls -l ../.git/hooks
      - name: Check Permissions of files in Git Repo.
        run: |
          git ls-tree HEAD