name: Update git-hooks if changes were made to .git-hooks folder.
on:
  push:
    paths: 
    - '.git-hooks/**'
jobs: 
  git-administration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing git-hooks folder to make sure that it copying files properly.
        run: |
          chmod +x ./.git-hooks/*
          cd .git-hooks
          ./install-hooks.sh
          ls -l ../.git/hooks
      - name: Checking permissions for post-checkout git-hook.
        run: |
          git ls-tree HEAD ./.git-hooks/post-checkout